name: Validate SPDX License year and company mention in currently changed files

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - assigned
      - review_requested

jobs:
  check-spdx-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Identify currently changed files and check licenses
        id: check-licenses
        run: |
          current_year=$(date +"%Y")  # Dynamically set current year for checking
          echo "Current year: $current_year"
          echo "current_year=$current_year" >> $GITHUB_ENV  # Export current year to environment variables
          missing_license_files=""
          excluded_paths=(
            "model_demos/cv_demos/yolo_v3/holli_src/utils.py"
            "model_demos/cv_demos/yolo_v3/holli_src/yolo_layer.py"
            "model_demos/cv_demos/yolo_v3/holli_src/utils.py"
            # Files to be ignored here
          )

          # Join excluded paths with |
          excluded_paths_regex=$(IFS="|"; echo "${excluded_paths[*]}")

          # Find changed Python files excluding the specified paths
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...HEAD | grep '\.py$' | grep -Ev "$excluded_paths_regex" || true)
          echo "Changed files: $changed_files"

          for file in $changed_files; do
            # Check if file contains the correct SPDX license identifier and the exact copyright statement with dynamic current year
            if ! grep -q "SPDX-License-Identifier: Apache-2.0" "$file"; then
              echo "Missing SPDX-License-Identifier in file: $file"
            fi
            if ! grep -q "SPDX-FileCopyrightText: © $current_year Tenstorrent AI ULC" "$file"; then
              echo "Missing or incorrect SPDX-FileCopyrightText in file: $file"
            fi
            if ! grep -q "SPDX-License-Identifier: Apache-2.0" "$file" || ! grep -q "SPDX-FileCopyrightText: © $current_year Tenstorrent AI ULC" "$file"; then
              missing_license_files="$missing_license_files$file\n"
            fi
          done
          echo -e "Missing license files: $missing_license_files"
          echo "missing_license_files=$missing_license_files" >> $GITHUB_ENV
          echo "Checked files for correct SPDX-License compliance."

      - name: Comment on PR about incorrect SPDX licenses
        if: env.missing_license_files != ''
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const missingFiles = process.env.missing_license_files.trim().split('\n').filter(Boolean).join('\n');
            const currentYear = process.env.current_year;
            const commentBody = `The following files are not compliant with the required licensing standards for ${currentYear} or do not contain the correct copyright text 'Tenstorrent AI ULC' within their license header:\n\n\`\`\`\n${missingFiles}\n\`\`\`\nPlease update the files accordingly. Your attention and cooperation in this matter are greatly appreciated.\n\nThank you.`;

            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: commentBody
            });

      - name: Fail the workflow if license issues are found
        if: env.missing_license_files != ''
        run: |
          echo "Failing the workflow due to non-compliance with SPDX license requirements."
          exit 1
